site_name: OPAL
docs_dir: docs
pages: 
  - [index.md, Home]  

  - [overview.md, Overview]
  - [installation.md, Installation]

  - [tutorial.md, 'Tutorials', Your first OPAL App]
  # - [plugins.md, 'Tutorials', Your first OPAL Plugin]

  - [guides/topic-guides.md, 'Data & Flow Guides', Index]
  - [guides/datamodel.md, 'Data & Flow Guides', Data Model]
  - [guides/flow.md, 'Data & Flow Guides', Flow]
  - [guides/roles_and_permissions.md, 'Data & Flow Guides', Roles & Permissions]
  - [guides/teams.md, 'Data & Flow Guides', Teams]
  - [guides/json_api.md, 'Data & Flow Guides', JSON API] 

  - [guides/forms.md, 'Presentation & Templating Guides', Forms]
  - [guides/lookup_lists.md, 'Presentation & Templating Guides', Lookup Lists]
  - [guides/episode_detail_views.md, 'Presentation & Templating Guides', Episode Detail Views]
  - [guides/list_views.md, 'Presentation & Templating Guides', Patient List Views]

  - [guides/components_overview.md, 'OPAL Guides', Component Overview]
  - [guides/plugins.md, 'OPAL Guides', Plugins]
  - [guides/plugins_list.md, 'OPAL Guides', Plugin List]

  - [reference/reference_guides.md, 'Reference', Index]
  - [reference/episode.md, 'Reference', The Episode model] 
  - [reference/subrecords.md, 'Reference', Subrecords ] 
  - [reference/opal_application.md, 'Reference', OpalApplication]
  - [reference/form_templatetags.md, 'Reference', Form helpers]
  - [reference/javascript_helpers.md, 'Reference', Javascript helpers]

theme: readthedocs
dev_addr: 0.0.0.0:8965
