site_name: OPAL
docs_dir: docs
pages: 
  - [index.md, Home]  

  - [overview.md, Overview]
  - [installation.md, Installation]

  - [tutorial.md, 'Tutorials', Your first OPAL App]
  # - [plugins.md, 'Tutorials', Your first OPAL Plugin]

  - [guides/topic-guides.md, 'Guides', Index]
  - [guides/datamodel.md, 'Guides', Data Model]
  - [guides/flow.md, 'Guides', Flow]
  - [guides/roles_and_permissions.md, 'Guides', Roles & Permissions]
  - [guides/teams.md, 'Guides', Teams]
  - [guides/forms.md, 'Guides', Forms]
  - [guides/lookup_lists.md, 'Guides', Lookup Lists]
  - [guides/episode_detail_views.md, 'Guides', Episode Detail Views]

  - [reference/reference_guides.md, 'Reference', Index]
  - [reference/opal_application.md, 'Reference', OpalApplication]
theme: readthedocs
dev_addr: 0.0.0.0:8965
